Set deployment target to iOS 9
feedhenry-templates/saml-ios-app pull request #31
Opened 2017-08-22 23:33 UTC by danielpassos

Related issues: 

* [FH-3921](https://issues.jboss.org/browse/FH-3921) - Set deployment target to iOS 9 on saml-ios-app

2017-08-23 10:30 UTC, jcesarmobile requested changes
Added a few comments
The Podfile has to be updated to iOS 9 too.

2017-08-23 10:30 UTC, jcesarmobile commented on .travis.yml
>  branches:
I think we should remove the "only" instead of adding new branches

2017-08-23 10:30 UTC, jcesarmobile commented on .travis.yml
Add 

```
before_install:
  - travis_wait pod repo update
```
That should fix the build fail.

2017-08-23 10:30 UTC, jcesarmobile commented on README.md
> +Prerequisites: fh-ios-sdk: 3.+, Xcode: 9+, iOS SDK: iOS 9+, CocoaPods: 1.3.0+
fh-ios-sdk: 4.+

2017-08-23 13:00 UTC, danielpassos commented on .travis.yml
>  branches:
Only is to prevent be annoyed when new release branch is created :/

2017-08-23 13:03 UTC, danielpassos commented on .travis.yml
:smirk: it's already there

2017-08-23 13:05 UTC, jcesarmobile commented on .travis.yml
Ah, true, then I don't know why it fails to find the dependency

2017-08-23 22:09 UTC, danielpassos commented
@jcesarmobile Suggestions applied and added @CircleCI

2017-08-24 09:24 UTC, jcesarmobile approved these changes

2017-08-24 09:32 UTC, jcesarmobile requested changes
As we have removed travis and added circle-ci we should change the badge.

I think this should work:

`[![CircleCI](https://circleci.com/gh/feedhenry-templates/saml-ios-app.svg?style=svg)](https://circleci.com/gh/feedhenry-templates/saml-ios-app)`

2017-08-24 10:04 UTC, jcesarmobile approved these changes

2017-08-24 10:05 UTC, jcesarmobile commented
We can fix the badge and add some more badges latter, so merging this

2017-08-24 10:05 UTC, merged